# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, choices=[('xhmm', 'XHMM'), ('oncotator', 'Oncotator'), ('mendelmd', 'Mendel,MD')], default='xhmm', max_length=50, null=True)),
                ('files', models.ManyToManyField(to='files.File')),
            ],
        ),
    ]
