# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 01:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 15, 1, 7, 28, 299214, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysis',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 15, 1, 7, 35, 535155, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
