# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0004_auto_20160115_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, to='files.File'),
        ),
    ]
